### ISSUE TITLE
Failed to install addon

### ISSUE THREAD

**Issue by gitprova0** [LordMike/MBW.BlueRiiot2MQTT#32]
Try installing the repository from the add-on store, after updating to "core-2021.1.4" and "supervisor-2021.01.4"  I receive this error:

404 Client Error for http+docker://localhost/v1.41/images/create?tag=0.9.2&fromImage=lordmike%2Fblueriiot2mqtt: Not Found ("manifest for lordmike/blueriiot2mqtt:0.9.2 not found: manifest unknown: manifest unknown")

**Comment by LordMike** [comment]
I'm not sure where you get `0.9.2` from.. The [hass-addons](https://github.com/LordMike/hass-addons/blob/02739c0e8ce501b1caad9c438e0a812db5b7385e/blueriiot2mqtt/config.json#L3) repo says `v0.9.2` .. so you should be getting that.

I've just checked, and tag `v0.9.2` does exist.. :|

**Comment by youngy00** [comment]
Hi,

I am also getting an error (previously working install) when trying to start.

`Failed to start addon
404 Client Error for http+docker://localhost/v1.40/containers/create?name=addon_dff6e9be_blueriiot2mqtt: Not Found ("No such image: lordmike/blueriiot2mqtt:0.9.2")`

**Comment by colesealeaf** [comment]
Yeah me too. I restored back to over a week ago when it was working and its still the same error :/

**Comment by LordMike** [comment]
Is it possible to get some details from the HASS store about what is about to be installed? 

.. Anywhere the version / tag can be shown?

* [Hub.docker.com](https://hub.docker.com/repository/registry-1.docker.io/lordmike/blueriiot2mqtt/tags?page=1&ordering=last_updated&name=0.9.2) shows the `v0.9.2`, which is shown to be last pulled 3h-1month ago.. I'm only using amd64, so others must be using the arm versions
* The [hass-addons config file](https://github.com/LordMike/hass-addons/blob/02739c0e8ce501b1caad9c438e0a812db5b7385e/blueriiot2mqtt/config.json#L3) specifies `v0.9.2` ... could it be possible HASS changed something that would strip the `v` ?

I don't run HASSIO myself, so I can't immediately test it :|

**Comment by LordMike** [comment]
If this goes on much longer, I'll just push to `0.9.2` as well -.-'

**Comment by Nicklas86** [comment]
I get the same error and it shows 0.9.2

**Comment by LordMike** [comment]
I've pushed a `0.9.2` tag. It should work out now :|

I'm still at a loss as to why.

**Comment by Nicklas86** [comment]
![blue](https://user-images.githubusercontent.com/76478422/105065101-ca841e00-5a7d-11eb-96aa-b5a0b46fe6ec.PNG)
Sorry no luck :(

**Comment by gitprova0** [comment]
Now I'm able to install it but still have problem running it:
404 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_e141bb7c_blueriiot2mqtt: Not Found ("No such image: lordmike/blueriiot2mqtt:0.9.2")

**Comment by LordMike** [comment]
`lordmike/blueriiot2mqtt:0.9.2` does exist now. Are you sure that f.ex. network isn't an issue?

**Comment by LordMike** [comment]
So I managed to install hassio myself in a VM, and I'm getting the same issue as you .. On start, it reports that issue. On the internet, some people are saying this could be a disk freespace issue, which it wasn't for me. To test, I opened the CLI on the system, logged on as root, and ran `docker run --rm lordmike/blueriiot2mqtt:v0.9.2` - which ran. So docker works.

I next tried `ha addons start dff6e9be_blueriiot2mqtt`, which seems to have worked..  I do not know why.

Now I can stop, and start the addon in the UI - with no issue. I can even reinstall it, and start it again..

I'm at a loss :|

![image](https://user-images.githubusercontent.com/1027111/105074105-3c616500-5a88-11eb-9b0e-625d1d32b97c.png)

In the logs above, the errors are when I tried it first from the UI. Then later, I started it using the console, after which the UI works.

**Comment by LordMike** [comment]
* [This page](https://community.home-assistant.io/t/home-assistant-in-a-vm-gives-404-on-docker/255937/10) has the same sudden 404's on things that use to work - referencing the supervisor / docker issue below, and also touches on DNS issues.
* [This page](https://community.home-assistant.io/t/404-error-on-supervisor-upgrade-addon-install/176456/10) reports on the disk issues, and potential corruptions in the install
* [This page](https://community.home-assistant.io/t/wipe-restore-supervisor-removes-and-fails-to-pull-and-start-homeassistant-image-container/254576/6) reports incompatibilities of docker 20.10 with the supervisor version HASS runs.

**Comment by gitprova0** [comment]
![IMG_20210119_192130](https://user-images.githubusercontent.com/74723009/105077305-9f54fb00-5a8c-11eb-9664-5d32dae57366.jpg)
I get this error when trying to run "docker run --rm lordmike/blueriiot2mqtt:v0.9.2"

**Comment by LordMike** [comment]
That's expected (as it's not configured). This proves the image was downloaded and can run.. 

Try `ha addons start dff6e9be_blueriiot2mqtt` .. the value there should be in your browsers address bar, when you visit the add-ons page for BlueRiiot2MQTT. I think it will be the same.

**Comment by colesealeaf** [comment]
Hi,
I tried some things, but still can't get it working. I don't have the 'v' anymore, which should be right? Any Idea's? The e141bb7c_blueriiot2mqtt is what is in my address bar, in the addon store.
![image](https://user-images.githubusercontent.com/73206769/105155918-499d5300-5b5f-11eb-8806-566b1cb712fa.png)

It states this on installation:
![image](https://user-images.githubusercontent.com/73206769/105157606-430fdb00-5b61-11eb-8bda-270c6d4bac99.png)

Then after you start it, and it fails it changes to:

![image](https://user-images.githubusercontent.com/73206769/105157807-72bee300-5b61-11eb-9638-663e13ac297d.png)

Just some info..

**Comment by LordMike** [comment]
It's totally weird they would remove the v - but I'm quite certain they still reference the correct image. 

As I found earlier, this is likely an issue with HASSIO, where something broke. 

You could try to find out which versions you're running:
* Docker, if it's 20.10 - it might be failing with incompatibility with supervisord

[This post](https://community.home-assistant.io/t/wipe-restore-supervisor-removes-and-fails-to-pull-and-start-homeassistant-image-container/254576/7) mentions how to downgrade docker, to 19.03. Which might fix stuff.. Note that I don't take any responsibility for anything that may come of this.

**Comment by LordMike** [comment]
I found that Hass has an alerts page, which at some point listed this incompatibility. The alert is gone, and I now found why: https://github.com/home-assistant/alerts.home-assistant.io/pull/256. They mentioned that Docker 20.10.1 and Supervisor 2020.12.7 fixed the issue.

You could therefore also try updating to get the newer versions.

Here is the [original alert](https://github.com/home-assistant/alerts.home-assistant.io/blob/d9b6597dbaab6679bbaa0e595b8c050c99d3d3b7/alerts/docker_2010.markdown) from HASS.

**Comment by gitprova0** [comment]
This is my configuration:
![Capture](https://user-images.githubusercontent.com/74723009/105216545-ffae7000-5b52-11eb-91c8-60ec05529e5b.JPG)
and this is the CLI output (e141bb7c_blueriiot2mqtt):
![IMG_20210120_153755](https://user-images.githubusercontent.com/74723009/105216619-19e84e00-5b53-11eb-95c7-abeae0113b62.jpg)

**Comment by Nicklas86** [comment]
Same problem for me :(

**Comment by LordMike** [comment]
Would it be possible for one or more of you to open a thread on the Hassio forums?

I'm quite certain the issue isn't with this project.

**Comment by gllmlbrt** [comment]
Hi, 
I have the exact same problem as mentionned earlier, not I can install the add-on. I even remove and re-added the add-on repository to start from scratch.
Note that I do not have the same problem with other custom repos for other add-ons.

Could it be that there is now a discrepancy between the version naming v0.9.2 and 0.9.2 for the reference in the add-on config.json here ?:
https://github.com/LordMike/hass-addons/blob/02739c0e8ce501b1caad9c438e0a812db5b7385e/blueriiot2mqtt/config.json#L3

Would that line not have to be `"version": "0.9.2",` instead of `"version": "v0.9.2",` ?

When simply listing the add-ons with `ha addons` i get this:
![image](https://user-images.githubusercontent.com/58825251/105307708-d4f90180-5bbc-11eb-9a81-e2103f9f00bf.png)

**Comment by LordMike** [comment]
I can try changing that to `0.9.2`. In reality, I was surprised to find that the version was expected to also be the tag of a docker image. So I went with the "v" prefix to indicate versions.

**Comment by LordMike** [comment]
I've changed it to `0.9.2` .. so you could try that. If it works, I'll just rename future versions to a non-prefixed kind.

**Comment by gllmlbrt** [comment]
Great !! That did the trick. It works fine. 
I deinstalled and deleted the repository. Restarted the core, and re-added the repository and installed. 
Re-pasted my config data, and started no problem. All is published on MQTT as expected !

Thanks!

**Comment by LordMike** [comment]
Fine. I'll mark new versions without a prefix..

Wow that's stupid.

**Comment by LordMike** [comment]
@youngy00 @colesealeaf @gitprova0 @Nicklas86 could you try again ? I've removed the prefix which should resolve the issue

I've also pushed version `0.10.0` - which includes a new command to do wifi readings.

**Comment by Nicklas86** [comment]
> @youngy00 @colesealeaf @gitprova0 @Nicklas86 could you try again ? I've removed the prefix which should resolve the issue
> 
> I've also pushed version `0.10.0` - which includes a new command to do wifi readings.

It works for me now! I will do the config later :) Thanx
